name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM every day
  workflow_dispatch:  # Allows manual triggering

# Add permissions block
permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Create Test Resources Directory
      run: |
        mkdir -p src/test/resources
        echo "Created test resources directory"
    
    - name: Download Test Files
      run: |
        # Download sample audio file (you can replace these URLs with your actual test files)
        curl -L "https://github.com/actions/upload-artifact/raw/main/test/test-files/hello.txt" -o src/test/resources/demo-audio.mp3
        curl -L "https://github.com/actions/upload-artifact/raw/main/test/test-files/hello.txt" -o src/test/resources/video.mp4
        echo "Downloaded test files"
    
    - name: Build with Maven
      run: mvn clean install -DskipTests -X
    
    - name: Run Tests
      run: mvn test -X
      env:
        MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"
    
    - name: Generate Allure Report
      run: mvn allure:report
    
    - name: Prepare Allure Report
      run: |
        mkdir -p temp-report
        cp -r target/site/allure-maven-plugin/* temp-report/
        cd temp-report
        zip -r ../allure-report.zip .
        cd ..
    
    - name: Send Email Report
      if: always()
      run: |
        # Send the email with the report
        java -cp target/classes:target/test-classes com.syntheticugc.utils.EmailUtil \
          "SyntheticUGC Test Report - $(date +'%Y-%m-%d %H:%M')" \
          "<html><body><h1>SyntheticUGC Test Report</h1><p>Please find attached the Allure test report.</p></body></html>" \
          allure-report.zip \
          true
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
    
    - name: Publish Test Results
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/target/surefire-reports/*.xml'
        check_name: 'Test Results'
        github_token: ${{ secrets.GITHUB_TOKEN }} 